### ISSUE TITLE
Add a human readable check error line in the logs when there are no Authentication Methods configured for a DUO User

### ISSUE THREAD

**Issue by bgironx15** [duosecurity/duo_openvpn_as#28]
Description:

When trying the authentication with a DUO User against the OpenVPN Access Server with AUTOPUSH = True, and the DUO User doesn't have any Authentication Methods configured, it fails, but no human readable check error line in the logs points out where the issue is

Steps to Reproduce:

    Setup a new DUO User
    Set AUTOPUSH = True in the DUO Script
    Add a policy for this user with no Authentication Methods configured for him
    Try logging in to the WebGUI to enroll the User
    Connection fails and no human readable check error line in the logs points out where the issue is

Logs:

```
Nov 26 19:39:00 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: initial auth request
Nov 26 19:39:00 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: pre-authentication for brandon.jimenez
Nov 26 19:39:01 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: secondary authentication required for user brandon.jimenez
Nov 26 19:39:01 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: Autopushing user: brandon.jimenez, autopush_factor=None
Nov 26 19:39:01 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: authentication for brandon.jimenez
Nov 26 19:39:01 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: Traceback (most recent call last):#012  File "<string>", line 676, in auth_and_update_result_structure#012  File "<string>", line 647, in auth#012  File "<string>", line 371, in json_api_call#012  File "<string>", line 590, in api_call#012  File "<string>", line 295, in api_call#012  File "<string>", line 222, in sign#012  File "<string>", line 213, in canonicalize#012  File "<string>", line 196, in canon_params#012  File "/usr/lib/python3.8/urllib/parse.py", line 871, in quote#012    return quote_from_bytes(string, safe)#012  File "/usr/lib/python3.8/urllib/parse.py", line 896, in quote_from_bytes#012    raise TypeError("quote_from_bytes() expected bytes")#012TypeError: quote_from_bytes() expected bytes
```

Proposed Solution:

Add a new log line that explains the issue better. For example:

```
Nov 27 07:31:08 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: initial auth request
Nov 27 07:31:08 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: pre-authentication for brandon.jimenez
Nov 27 07:31:09 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: secondary authentication required for user brandon.jimenez
Nov 27 07:31:09 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: Autopushing user: brandon.jimenez, autopush_factor=None
Nov 27 07:31:09 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: There are no Authentication Methods configured for user brandon.jimenez. Please check your Policy on DUO Side
Nov 27 07:31:09 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: authentication for brandon.jimenez
Nov 27 07:31:09 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: Traceback (most recent call last):#012  File "<string>", line 676, in auth_and_update_result_structure#012  File "<string>", line 647, in auth#012  File "<string>", line 371, in json_api_call#012  File "<string>", line 590, in api_call#012  File "<string>", line 295, in api_call#012  File "<string>", line 222, in sign#012  File "<string>", line 213, in canonicalize#012  File "<string>", line 196, in canon_params#012  File "/usr/lib/python3.8/urllib/parse.py", line 871, in quote#012    return quote_from_bytes(string, safe)#012  File "/usr/lib/python3.8/urllib/parse.py", line 896, in quote_from_bytes#012    raise TypeError("quote_from_bytes() expected bytes")#012TypeError: quote_from_bytes() expected bytes
```

I added this line in the DUO Script:

`Nov 27 07:31:09 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: There are no Authentication Methods configured for user brandon.jimenez. Please check your Policy on DUO Side`

It would be really helpful for troubleshooting to have this line or something similar added in the DUO Script natively

**Comment by AaronAtDuo** [comment]
@bgironx15 This sounds like a good idea.  Just to make sure I'm on the same page, you're saying that at line https://github.com/duosecurity/duo_openvpn_as/blob/master/duo_openvpn_as.py#L729, if the autopush_factor is None, we should emit an error message such as the one you suggest?  And then probably fail the authentication more gracefully than by triggering a stack trace?

**Comment by bgironx15** [comment]
Hello @AaronAtDuo thanks for the response

Yes, for example, this is what I did to workaround the issue:

From this:

                if AUTOPUSH:
                    autopush_factor = response.factors.get('default')

                    log("Autopushing user: %s, autopush_factor=%s" % (username, autopush_factor))

                    authret = auth_and_update_result_structure(username, autopush_factor, ipaddr, authret)

To this:

                if AUTOPUSH:
                    autopush_factor = response.factors.get('default')

                    log("Autopushing user: %s, autopush_factor=%s" % (username, autopush_factor))

                    if autopush_factor is None:  # Check if autopush_factor is None (actual Python None, not string "None")
                        log(f"There are no Authentication Methods configured for user {username}. Please check your Policy on DUO Side")

                    authret = auth_and_update_result_structure(username, autopush_factor, ipaddr, authret)

And yes, failing the authentication more gracefully than by triggering a stack trace is another good idea

**Comment by AaronAtDuo** [comment]
@bgironx15 How does PR #29  look?

**Comment by bgironx15** [comment]
Hello @AaronAtDuo looks good. See below:

+ Attempt from Client WebUI when there is no Policy assigned for my user:

![Image](https://github.com/user-attachments/assets/8ec15e89-b355-446a-acc5-b806a54ad4b9)

+ Logs from /var/log/syslog:

Apr 14 15:30:19 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: initial auth request
Apr 14 15:30:19 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: pre-authentication for brandon.jimenez
Apr 14 15:30:19 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: secondary authentication required for user brandon.jimenez
Apr 14 15:30:19 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: No autopush factors are available in Duo policy for user brandon.jimenez



+ Attempt from VPN Client when there is no Policy assigned for my user:

![Image](https://github.com/user-attachments/assets/1c1cef75-7453-4456-853c-7df0096e3a57)

+ Logs from /var/log/syslog:

Apr 14 15:32:46 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: initial auth request
Apr 14 15:32:46 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: pre-authentication for brandon.jimenez
Apr 14 15:32:46 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: secondary authentication required for user brandon.jimenez
Apr 14 15:32:46 openvpn-access-server-Brandon2XX openvpnas: Duo OpenVPN_AS: No autopush factors are available in Duo policy for user brandon.jimenez
